project_id = "pxmibkknptxuyjltordz"

[functions.analyze-deal]
verify_jwt = false

[functions.analyze-property]
verify_jwt = false

[functions.generate-property-description]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false
